# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/hover.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainpage(object):
    def setupUi(self, mainpage):
        mainpage.setObjectName("mainpage")
        mainpage.resize(1195, 860)
        self.label = QtWidgets.QLabel(mainpage)
        self.label.setGeometry(QtCore.QRect(0, -10, 1201, 871))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setStyleSheet("image: url(:/images/Static/thumb2-violet-neon-circle-4k-3d-art-creative-neon-rings.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/Static/thumb2-violet-neon-circle-4k-3d-art-creative-neon-rings.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(mainpage)
        self.frame_2.setGeometry(QtCore.QRect(590, 90, 551, 671))
        self.frame_2.setStyleSheet("background-color: rgb(6, 6, 6);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.contact_label = QtWidgets.QLabel(self.frame_2)
        self.contact_label.setGeometry(QtCore.QRect(420, 40, 81, 31))
        self.contact_label.setStyleSheet("QLabel{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"}\n"
"\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.contact_label.setObjectName("contact_label")
        self.about_label = QtWidgets.QLabel(self.frame_2)
        self.about_label.setGeometry(QtCore.QRect(320, 40, 81, 31))
        self.about_label.setStyleSheet("QLabel{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"}")
        self.about_label.setObjectName("about_label")
        self.work_label = QtWidgets.QLabel(self.frame_2)
        self.work_label.setGeometry(QtCore.QRect(230, 40, 81, 31))
        self.work_label.setStyleSheet("QLabel{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"color: white;\n"
"}")
        self.work_label.setObjectName("work_label")
        self.interested_label = QtWidgets.QLabel(self.frame_2)
        self.interested_label.setGeometry(QtCore.QRect(50, 110, 231, 31))
        self.interested_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.interested_label.setObjectName("interested_label")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 160, 141, 41))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"border: 2px solid rgb(113, 113, 113);\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border: 2px solid white;\n"
"font: bold;\n"
"}\n"
"")
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(210, 160, 111, 41))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"border: 2px solid rgb(113, 113, 113);\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border: 2px solid white;\n"
"font: bold;\n"
"}\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 160, 111, 41))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"border: 2px solid rgb(113, 113, 113);\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border: 2px solid white;\n"
"font: bold;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 220, 141, 41))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"border: 2px solid rgb(113, 113, 113);\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border: 2px solid white;\n"
"font: bold;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 220, 81, 41))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"color: rgb(113, 113, 113);\n"
"background-color: none;\n"
"border: 2px solid rgb(113, 113, 113);\n"
"transition:0.3s;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: white;\n"
"border: 2px solid white;\n"
"font: bold;\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.send_btn = QtWidgets.QPushButton(self.frame_2)
        self.send_btn.setGeometry(QtCore.QRect(60, 590, 171, 41))
        self.send_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";\n"
"\n"
"")
        self.send_btn.setObjectName("send_btn")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 290, 411, 41))
        self.lineEdit_4.setStyleSheet("color: rgb(113, 113, 113);\n"
"border-bottom: 2px solid rgb(113, 113, 113);\n"
"border-top: hidden; \n"
"background-color: rgb(6, 6, 6);\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 370, 411, 41))
        self.lineEdit_5.setStyleSheet("color: rgb(113, 113, 113);\n"
"border-bottom: 2px solid rgb(113, 113, 113);\n"
"border-top: hidden; \n"
"background-color: rgb(6, 6, 6);\n"
"")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 450, 411, 41))
        self.lineEdit_6.setStyleSheet("color: rgb(113, 113, 113);\n"
"border-bottom: 2px solid rgb(113, 113, 113);\n"
"border-top: hidden; \n"
"background-color: rgb(6, 6, 6);\n"
"\n"
"")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(90, 520, 231, 41))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(50, 520, 41, 41))
        self.label_12.setStyleSheet("image: url(:/images/Static/paperclipblue.png);")
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(mainpage)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 401, 241))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(mainpage)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 241, 61))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(mainpage)
        self.label_4.setGeometry(QtCore.QRect(60, 700, 321, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(mainpage)
        QtCore.QMetaObject.connectSlotsByName(mainpage)

    def retranslateUi(self, mainpage):
        _translate = QtCore.QCoreApplication.translate
        mainpage.setWindowTitle(_translate("mainpage", "Form"))
        self.contact_label.setText(_translate("mainpage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Contacts</span></p></body></html>"))
        self.about_label.setText(_translate("mainpage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">About</span></p></body></html>"))
        self.work_label.setText(_translate("mainpage", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Works</span></p></body></html>"))
        self.interested_label.setText(_translate("mainpage", "<html><head/><body><p><span style=\" font-size:14pt;\">I\'m interested in....</span></p></body></html>"))
        self.pushButton_7.setText(_translate("mainpage", "UVUX Design"))
        self.pushButton_8.setText(_translate("mainpage", "Website"))
        self.pushButton_9.setText(_translate("mainpage", "Branding "))
        self.pushButton_10.setText(_translate("mainpage", "Design system"))
        self.pushButton_11.setText(_translate("mainpage", "Other"))
        self.send_btn.setText(_translate("mainpage", "Send Request "))
        self.lineEdit_4.setPlaceholderText(_translate("mainpage", "Your Name "))
        self.lineEdit_5.setPlaceholderText(_translate("mainpage", "Your Email"))
        self.lineEdit_6.setPlaceholderText(_translate("mainpage", "Tell Us More about the project"))
        self.label_11.setText(_translate("mainpage", "<html><head/><body><p><span style=\" font-size:12pt;\">Add Attachment </span></p></body></html>"))
        self.label_12.setText(_translate("mainpage", "TextLabel"))
        self.label_2.setText(_translate("mainpage", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Have a project?</span></p><p><span style=\" font-size:22pt; font-weight:600;\">We Would Love </span></p><p><span style=\" font-size:22pt; font-weight:600;\">To Help.</span></p></body></html>"))
        self.label_3.setText(_translate("mainpage", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">ZERO GRAVITY</span></p></body></html>"))
        self.label_4.setText(_translate("mainpage", "<html><head/><body><p><span style=\" font-size:14pt;\">zergravitydsgn@gmail.com</span></p></body></html>"))
import resources1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainpage = QtWidgets.QWidget()
    ui = Ui_mainpage()
    ui.setupUi(mainpage)
    mainpage.show()
    sys.exit(app.exec_())
